# File used for default debugging settings.
# This WILL NOT (and SHOULD NOT) be used in production. It contains keys
# that are valid but should not be used in a real production environment.

# This will also be used as the JWT key (WILL log you out if you change this value).
secret_key = "dH+kbvuRgr6z/OQaycGZEjMFKRFnhBlJJha9CYnWCNNpnsGHSGcOb+HZsmwLGoOf84Xz5d1EGMT/1EnVJxoDFw=="
db_pepper = ""

template_dir = "templates"

[debug]
additional_root_team = []
bypass_email_validation = ["*"]

[s3]
region = "http://localhost:9000"
access_key = "<USE_ENV_VARS>"
secret_key = "<USE_ENV_VARS>"

[databases.retronomicon_db]
url = "postgres://local_user:mysecretpassword@localhost:5432/local_retronomicon"
