[default]
# The URL of the frontend. This is used to generate links.
base_url = "/"

# Members (emails) of the root team.
root_team = [
    "hans@larsen.online",
    "hans@retronomicon.dev",
]
root_team_id = 1

[default.limits]
# 24 Megabytes
json = 25165824
# 48 Megabytes
file = 50331648

[default.databases]
# retronomicon_db is set automatically from the env variables.

[default.oauth.github]
provider = "GitHub"
client_id = "<USE_ENV_VARS>"
client_secret = "<USE_ENV_VARS>"
redirect_uri = "http://localhost:8000/api/auth/github"

[default.oauth.google]
provider = "Google"
client_id = "<USE_ENV_VARS>"
client_secret = "<USE_ENV_VARS>"
redirect_uri = "http://localhost:8000/api/auth/google"

[default.oauth.patreon]
auth_uri = "https://www.patreon.com/oauth2/authorize"
token_uri = "https://www.patreon.com/api/oauth2/token"
client_id = "<USE_ENV_VARS>"
client_secret = "<USE_ENV_VARS>"
redirect_uri = "http://localhost:8000/api/auth/patreon"

#[default.oauth.microsoft]
#provider = "Microsoft"
#client_id = "<USE_ENV_VARS>"
#client_secret = "<USE_ENV_VARS>"
#redirect_uri = "http://localhost:8000/api/auth/microsoft"
