[default]
# The URL of the frontend. This is used to generate links.
base_url = "http://localhost:8000/"

# Members (emails) of the root team. Use `*` and `?` as wildcards.
root_team = [
    "*@retronomicon.dev",
    "*@retronomicon.land",
]
root_team_id = 1

[default.databases.retronomicon_db]
pool_size = 5

[default.smtp]
port = 587
# The login info should be set through an environment variable.
from = "No Reply <no-reply@retronomicon.land>"
email_verification_template = "../templates/email-verification.hbs"

[default.limits]
# 24 Megabytes
json = 25165824
# 48 Megabytes
file = 50331648

[default.oauth.github]
provider = "GitHub"
client_id = "<USE_ENV_VARS>"
client_secret = "<USE_ENV_VARS>"
redirect_uri = "http://localhost:8000/api/auth/github"

[default.oauth.google]
provider = "Google"
client_id = "<USE_ENV_VARS>"
client_secret = "<USE_ENV_VARS>"
redirect_uri = "http://localhost:8000/api/auth/google"

[default.oauth.patreon]
auth_uri = "https://www.patreon.com/oauth2/authorize"
token_uri = "https://www.patreon.com/api/oauth2/token"
client_id = "<USE_ENV_VARS>"
client_secret = "<USE_ENV_VARS>"
redirect_uri = "http://localhost:8000/api/auth/patreon"

#[default.oauth.microsoft]
#provider = "Microsoft"
#client_id = "<USE_ENV_VARS>"
#client_secret = "<USE_ENV_VARS>"
#redirect_uri = "http://localhost:8000/api/auth/microsoft"
