
# for Apple Silicon Macs
# To use, make sure to install libpq with `brew install libpq`
[target.aarch64-apple-darwin]
rustflags = ["-L", "/opt/homebrew/opt/libpq/lib"]

# for Intel Macs
# To use, make sure to install libpq with `brew install libpq`
[target.x86_64-apple-darwin]
rustflags = ["-L", "/usr/local/opt/libpq/lib"]
